on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/*"
      - "script/*"
      - "patches/*"
  workflow_dispatch:
    inputs:
      skip_release:
        description: 'Skip release related steps? (true/false)'
        required: true
        default: 'false'

env:
  version: m105-f204b137b9

jobs:
  
  windows:
    runs-on: windows-2019
    strategy:
      matrix:
        build_type: [Debug, Release]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: python3 script/check_release.py --version ${{ env.version }} --build-type ${{ matrix.build_type }}
        if: ${{ github.event.inputs.skip_release != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: microsoft/setup-msbuild@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - shell: bash
        run: python3 script/checkout.py --version ${{ env.version }}
      - shell: bash
        run: python3 script/build.py --build-type ${{ matrix.build_type }}
      - shell: bash
        run: python3 script/archive.py --version ${{ env.version }} --build-type ${{ matrix.build_type }}
      - uses: actions/upload-artifact@v2
        with:
          name: Skia-${{ env.version }}-windows-${{ matrix.build_type }}-x64.zip
          path: '*.zip'
      - shell: bash
        run: python3 script/release.py --version ${{ env.version }} --build-type ${{ matrix.build_type }}
        if: ${{ github.event.inputs.skip_release != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
